Algoritmo "Circulo"
// Disciplina   : Aula
// Professor   : Jailson
// Descrição   : Ler o raio e calcular a area de um circulo
// Autor(a)    : Raquel Luna
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
 area,raio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o valor do raio de um circulo:")
 leia(raio)
 area<-raio*raio*pi
 escreval("O valor da area de um circulo é:", area)

Fimalgoritmo