Algoritmo "Exercicio Manzano 2"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Tabuada
// Autor(a)    : Raquel Luna
// Data atual  : 03/04/2024
Var

   numero,contadora:inteiro

Inicio

   escreval("digite um numero que deseja saber a tabuada :")
   leia(numero)
   para contadora de 1 ate 10 passo 1 faca
   escreval(numero, " X ",contadora, " = ",numero*contadora)
   fimpara



Fimalgoritmo