Algoritmo "Quadrado"
// Disciplina   : aula
// Professor   : Jailson
// Descrição   : Ler um lado e calcular a  area de um quadrado
// Autor(a)    : Raquel Luna
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
 lado:real
 area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o valor do lado de um quadrado:")
 leia(lado)
 area<-lado^2
 escreval("O valor da area de um quadrado é:",area)

Fimalgoritmo